### ISSUE TITLE
Cant pip install the library 

### ISSUE THREAD

**Issue by Rahulm1998** [coherentgraphics/python-libcpdf#1]
Not able to pip install the library as following error is shown:

ERROR: Could not find a version that satisfies the requirement pycpdflib (from versions: none)
ERROR: No matching distribution found for pycpdflib

**Comment by johnwhitington** [comment]
I see

```
gorge:repos john$ pip install pycpdflib
Collecting pycpdflib
  Downloading pycpdflib-2.5-py3-none-any.whl (17 kB)
Installing collected packages: pycpdflib
Successfully installed pycpdflib-2.5
WARNING: You are using pip version 21.3.1; however, version 22.0.4 is available.
You should consider upgrading via the '/Library/Frameworks/Python.framework/Versions/3.8/bin/python3 -m pip install --upgrade pip' command.
```

What version of Python are you using?

**Comment by Rahulm1998** [comment]
I am currently using python 3.7

**Comment by johnwhitington** [comment]
Pycpdflib needs Python 3.8 or later. You can see this on the left sidebar of the pycpdflib page:

https://pypi.org/project/pycpdflib/

Pip's error is rather cryptic, though, I agree.

**Comment by Rahulm1998** [comment]
Oh understood thanks for the help !
